name: Publish Repo

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Configure AWS
      uses: jakejarvis/s3-sync-action@master
      with:
        aws-access-key-id: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - name: Copy files
      run: aws s3 sync . s3://${{ secrets.DEPLOY_AWS_S3_BUCKET }}/ --no-progress --acl public-read --follow-symlinks --delete --exclude '.git/*' --exclude '.github/*' --content-type 'text/plain'